### PR TITLE
Remove $FreeBSD$ tags

### PR DESCRIPTION
**Pull request by stesser**
For some reason my my pull-request contains previously applied changes and all my attempts to get my fork synchronized to the official repository failed. (I hate git the more I have to use it!)

Only the commit from May 3, 2022 (11336bc5d7) should be contained in this pull request.

### CODE REVIEW

**Comment by lsalvadore** [comment]
I am sorry, watching the repository was disabled and I only saw your pull request now. Now I am watching the repository, so this should not happen again.

I will review your pull request as soon as possible.

**Comment by lsalvadore** [comment]
I approve the commit and I will do my best to merge it properly.

Syncronizing repositories is not an easy task indeed. I do it without using the GitHub interface: in my local git repository I set two different remotes (one for the original repository and own for my own fork), then syncronize the branch in my fork with the branch in the original repository using git rebase. You might want to try that.

Before merging this pull request, I would like to wait for the licensing issue in pull request #9 (about which you should already be aware, if not please review it) to be fixed. Once this is done, I will proceed with the merging.

**Comment by bsdimp** [comment]
This looks good to my eye, but I did scan it pretty fast.

**Comment by lsalvadore** [comment]
Pull request #9 has been merged. I will merge your changes soon as you confirm that you are fine with the license. Thanks.

**Comment by lsalvadore** [comment]
Merged manually with commit f3d02cf21977f642d3d546b69203469be0c19828. Thanks.

**Pull request closed without merging**
