### PR TITLE
Convert all calendar data files to UTF-8

### PR DESCRIPTION
**Pull request by stesser**
Files in other encodings have been removed after checking that they
are identical to the UTF-8 versions converted back to the original
encoding.

A new calendar.austria file has been added to be able to use the
typical name to refer to the files in de_AT.UTF-8.

The purpose of this conversion is to ease maintenance of these files 
due to only using a single standard encoding.

### CODE REVIEW

**Comment by lsalvadore** [comment]
It looks good. I haven't checked that the UTF-8 converted files are identical to the corresponding ones you that removed: I trust that you checked it carefully.

Since I see the pull request has been opened a long time ago, could you please confirm that you still want it merged before I proceed?

**Comment by stesser** [comment]
Yes, the pull request is still relevant, but I had hoped for Warner Losh to state his opinion whether it is wise to make support of UTF-8 a requirement. Some users may still have 8 bit locales that are not compatible with UTF-8 and may work exclusively in that locale without reliance on iconv features.

All entries have been verified by translating them back to the original locales.

I have just noticed that there was a commit to the French calendar that needs to be included in the new files.
BTW: Why was this new entry added without the year (1789) of that incident as recorded for other historic events?

I have updated the pull request and resolved the conflict for that 1789-08-04 entry ...

**Comment by lsalvadore** [comment]
Try sending Warner a mail: he might be able to find a minute to give his opinion about it. I am also mentioning @bsdimp, so maybe he will get a notification about this issue.

If it is indeed an issue to assume UTF-8 support, maybe it might make sense to maintain two branches and to provide a port option to choose between them? Of course, this increases both the port's and the repository's complexity, so it must be thought carefully.

About the new French date, I am sorry, I did not notice the other entries had the year reported at the end of line. I will be more careful next time. By the way, it is not the only entry missing the year and both pauamma and me spotted other things to correct.
In case we eventually renounce to the UTF-8 conversion and close the pull request without committing it, we must remember to bring into the repository at least that correction you spotted.

Also, since you maintain deskutils/calendar, I think it would be wise if you requested write access to this repository as I did recently through bugzilla.

**Comment by bsdimp** [comment]
I think this is a good idea. I wasn't sure at first, and then forgot to followup once I made up my mind.

**Comment by stesser** [comment]
Yes, write access to this repository might simplify things for me, especially if I'm going to add the UK bank holiday feature requested by some user.
But I have checked the sources for a way to add such a feature, and the parser is already quite complex and adding that feature would add significant further complexity ...

**Comment by lsalvadore** [comment]
Merged. Feel free to tell me if you need anything else while you are still without write access. Maybe a new tag release?

As for the bank issue, I have already stated my mind in the relevant issue and I have not changed it, but if you want to try I will be glad to help you if you need.

**Pull request merged**
