### PR TITLE
Add August 4 entry for France.

### PR DESCRIPTION
**Pull request by pauamma**
Very important French Revolution event, leading to major changes throughout
French society.
References:
- Dictionnaire critique de la Révolution française (François Furet/Mona Ozouf)
- A Critical Dictionary of the French Revolution (François Furet)

### CODE REVIEW

**Comment by lsalvadore** [comment]
This surely is a very important date in French History, but I would not define it "much more relevant" than July 14th: the French Revolution is a very long historical event and the Storming of the Bastille is not celebrated as the day when the Bastille was attacked as much as a symbolical event when the Revolution begun. It was celebrated the first time in 1790 and today it is still a national holiday in France.
I would edit the commit message to remove the importance comparison: this is subjective.

On the other hand, if you are interested in adding events from the French Revolution, I think the date of the Declaration of the Rights of Man and of the Citizen (August 26th of 1789) is also missing. Personally, I consider it even more important than August 4th, but again this is subjective.
(And I see that right of vote for women in the US has been reported twice on August 26th: you might want to fix it while here).

**Comment by pauamma** [comment]
> This surely is a very important date in French History, but I would not define it "much more relevant" than July 14th: the French Revolution is a very long historical event and the Storming of the Bastille is not celebrated as the day when the Bastille was attacked as much as a symbolical event when the Revolution begun. It was celebrated the first time in 1790 and today it is still a national holiday in France. I would edit the commit message to remove the importance comparison: this is subjective.

Updated the draft commit message. Thanks.
> On the other hand, if you are interested in adding events from the French Revolution, I think the date of the Declaration of the Rights of Man and of the Citizen (August 26th of 1789) is also missing. Personally, I consider it even more important than August 4th, but again this is subjective.

I'm not going to, because:
- there were several versions of it between 1789 and 1791, so it's not at all clear to me that the date of the first version is the right one.
- is it more important than the ones that followed it in 1793 and 1795, or come to think of the Charter granted in 1815 after the Restoration, which held for about 15 years IIRC?

> (And I see that right of vote for women in the US has been reported twice on August 26th: you might want to fix it while here).

I'm going to do that in a once-over since I spotted some other nits (Saint Columba is misspelled, for one).

**Comment by lsalvadore** [comment]
> > On the other hand, if you are interested in adding events from the French Revolution, I think the date of the Declaration of the Rights of Man and of the Citizen (August 26th of 1789) is also missing. Personally, I consider it even more important than August 4th, but again this is subjective.
> 
> I'm not going to, because:
> 
> * there were several versions of it between 1789 and 1791, so it's not at all clear to me that the date of the first version is the right one.

I wasn't aware that there are multiple versions: I only knew about the version of 1789 and Olympe De Gouges' Declaration of the Rights of Woman and of the Female Citizen, but I see that this is not what you are referencing.

August 26th 1789 is the date that I have always been teached and I tend to consider first versions more important to later corrections.

> * is it more important than the ones that followed it in 1793 and 1795, or come to think of the Charter granted in 1815 after the Restoration, which held for about 15 years IIRC?

I would say it is more important than the Charter as
* it seems to me that the Declaration has an universal scope (think to article 1: "Les hommes...", not "Les français..."), while the Charter only regards France (and other countries had other similar documents);
* the Declaration is considered a milestone in the History of Human Rights.

It seems it is also recognized by UNESCO:
http://www.unesco.org/new/fr/communication-and-information/flagship-project-activities/memory-of-the-world/register/full-list-of-registered-heritage/registered-heritage-page-6/original-declaration-of-the-rights-of-man-and-of-the-citizen-1789-1791/

But you are free to not add this event of course: again, importance is subjective.
Actually, it does not seems to me that the list of events is based on importance only. For example I read "07/17 Disneyland opens, 1955": while Disneyland surely has been enjoyed but lots of children in the World, I don't think it changed World History.

I would recommend to not overthink it: just add the events that you like. You could even create a calendar file dedicated to the French Revolution only, with all details, if you enjoy the topic.

**Comment by pauamma** [comment]
I'll think about it and maybe add it if/when I have a moment. Meanwhile, what do you think about committing this as it currently stands?

**Comment by lsalvadore** [comment]
I agree about commiting it and if you have write access feel free to proceed (this is not an official approval, but only a review: as a mentored committer, I cannot give any kind of approval yet; later I will be able to give ports approval, if you need it).
I don't have write access to the repository: if you need me to get it just tell me and I will try to get it.

**Comment by pauamma** [comment]
> I don't have write access to the repository: if you need me to get it just tell me and I will try to get it.

I don't have write access to this repo either and I'm not sure who does, so if you can get it and commit it, I'd appreciate that. Or I can ask who does - maybe the port maintainer in the ports tree knows that.

**Comment by lsalvadore** [comment]
Merged, thanks!

**Comment by lsalvadore** [comment]
And I merged it wrong: it has been merged with the original commit message. Sorry about that, I hope this is not a problem.

I must be more careful with commit messages.

**Pull request merged**
